# Generated by Django 4.2.9 on 2026-06-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='badge',
            field=models.CharField(choices=[('nouveau_membre', 'Nouveau membre'), ('etudiant_actif', 'Étudiant actif'), ('etudiant_solidaire', 'Étudiant solidaire'), ('mentor', 'Mentor'), ('expert', 'Expert')], default='nouveau_membre', max_length=30),
        ),
    ]
