# Generated by Django 4.2.9 on 2026-06-15 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_message'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='messages_sender__6ae55a_idx',
            old_name='accounts_message_sender_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='messages_recipie_ef005d_idx',
            old_name='accounts_message_recipient_idx',
        ),
    ]
